### ISSUE TITLE
use endianess of mcu/ARM in PC_updater_tool

### ISSUE THREAD

**Issue by Darthyson** [selfbus/software-arm-lib#62]
let the mcu/ARM use the data in its own endianess and let the Updater send it in the right order. Detect endianess on one of the first commands. memcpy and simple casts can then be used on the mcu, which might save some memory

_Originally posted by @gnampf1 in https://github.com/selfbus/software-arm-lib/pull/59#discussion_r1141144507_

**Comment by dallmair** [comment]
To be honest, I'm not a big fan of this idea.

First, from an architectural standpoint, a communication protocol should have a single well-defined endianness. This simplifies a bunch of things for us humans, e.g. one can get used to reading the protocol in hex without continuously checking which endianness is in use. Or think about sharing small fragments of protocol logs -- these would be harder to understand when they exclude the endianness handshake command.

Second, I doubt the listed pros even exist. Two types of things are transmitted in the protocol: Sequences of bytes and numbers. Bytes are independent of endianness and can always be `memcpy`'ed, already today, so no change. Numbers would indeed change depending on endianness, however there is a big issue with all types of numbers that are larger than a single byte, and that is their *alignment requirements*. One *cannot* simply cast any pointer to an (e.g.) `uint16_t`, because that pointer must be aligned on a 16-bit boundary. Same for 32-bit (like the CRC). So to reap the benefits of adding endianness to the communication protocol, we would need to ensure that all these numbers are always aligned on the respective boundaries in the protocol -- which is a really bad idea, and I hope you agree with me. (If not, please remember that Extended Frames have a 2-byte header whereas Standard Frames only have a 1-byte header, so aligning things in the protocol in a general way is hard or outright impossible.)

Different platforms have different alignment requirements. Some only exhibit a measurable performance difference when accessing unaligned data, others (like Cortex-M0) strictly forbid them altogether. Our lovely LPC1115 hard faults right away on unaligned memory accesses (see UM10398 28.5.3.4: "Any attempt to perform an unaligned memory access operation results in a HardFault exception.").

**Comment by dallmair** [comment]
Some more data as I just stumbled over it:
* KNX-TP uses Big Endian
* Gira Smoke Detector uses Big Endian
* out-cs-bim112 uses Little Endian, but it simply serializes values into memory and reads them back out again, so endianness actually does not matter

So from what I can tell, Bootloader is the only component right now that sends data in Little Endian over the wire.

**Comment by Darthyson** [comment]
Thank you for your research. Considering everything you wrote, the only conclusion is to close the issue. Especially considered the additional code size to stay compatible with the current protocol.

**Comment by dallmair** [comment]
Thanks for your thoughts, doing so now.
